/**
 * Call to Arms: Cross-Reference Based Hook Points
 * Auto-generated by CrossReferenceAnalyzer.java
 * These are "hub" functions that connect to many subsystems
 */

#pragma once
#include <cstdint>

namespace COA {
namespace XRefHooks {

// Hub functions (call many subsystems)
constexpr uintptr_t AI_TEAM_COORDINATION_140C367A0 = 0x00C367A0; // calls 80 funcs
constexpr uintptr_t AI_SQUAD_BEHAVIOR_140A0A180 = 0x00A0A180; // calls 63 funcs
constexpr uintptr_t AI_TEAM_COORDINATION_140C28D20 = 0x00C28D20; // calls 62 funcs
constexpr uintptr_t AI_TEAM_COORDINATION_1402EF630 = 0x002EF630; // calls 57 funcs
constexpr uintptr_t PARSE_UNIT_VETERANCY_140949B50 = 0x00949B50; // calls 57 funcs
constexpr uintptr_t AI_ATTACK_BEHAVIOR_14097F690 = 0x0097F690; // calls 55 funcs
constexpr uintptr_t AI_TEAM_COORDINATION_14028F830 = 0x0028F830; // calls 52 funcs
constexpr uintptr_t PARSE_RELOAD_TIME_1407E4B10 = 0x007E4B10; // calls 52 funcs
constexpr uintptr_t AI_OBJECTIVE_HANDLER_140BBDB40 = 0x00BBDB40; // calls 51 funcs
constexpr uintptr_t AI_MOVEMENT_SYSTEM_1405C88C0 = 0x005C88C0; // calls 50 funcs
constexpr uintptr_t AI_FSM_1407F27A0 = 0x007F27A0; // calls 49 funcs
constexpr uintptr_t PARSE_WEAPON_RANGE_1401B4C80 = 0x001B4C80; // calls 49 funcs
constexpr uintptr_t AI_CONTROLLER_14022C300 = 0x0022C300; // calls 47 funcs
constexpr uintptr_t PARSE_ROTATION_SPEED = 0x001B3230; // calls 46 funcs
constexpr uintptr_t AI_TEAM_COORDINATION_140CE9D60 = 0x00CE9D60; // calls 46 funcs
constexpr uintptr_t AI_THREAT_ASSESSMENT_140B8CB60 = 0x00B8CB60; // calls 44 funcs
constexpr uintptr_t AI_TEAM_COORDINATION_14051C270 = 0x0051C270; // calls 44 funcs
constexpr uintptr_t AI_VEHICLE_CONTROLLER_14018D0C0 = 0x0018D0C0; // calls 43 funcs
constexpr uintptr_t AI_CONTROLLER_14093AF10 = 0x0093AF10; // calls 43 funcs
constexpr uintptr_t AI_SQUAD_BEHAVIOR_140CB4000 = 0x00CB4000; // calls 42 funcs

} // namespace XRefHooks
} // namespace COA
