// Call to Arms: Gates of Hell - Structure Definitions
// Auto-generated by StructureFinder.java
// Base structure with known offsets from Parse functions

#pragma once
#include <cstdint>

// Collect all unique offsets
struct GameEntity {
    // Known offsets from reverse engineering:

    void* field_1; // Used by: Damage_Stats_1401f1a30, Reload_Time_14091b240, Damage_Stats_140a...
    void* field_2; // Used by: Damage_Stats_1401f1a30, Damage_Stats_140a62d30, Armor_Values_140...
    void* field_3; // Used by: Damage_Stats_1401f1a30, Reload_Time_14091b240, Damage_Stats_140a...
    void* field_4; // Used by: Damage_Stats_1401f1a30, Armor_Values_1400a2100, Armor_Values_140...
    void* field_5; // Used by: Armor_Values_1409fd220, Inventory_Base_140b25a80, Inventory_Base...
    void* field_6; // Used by: Damage_Stats_1401f1a30, Armor_Values_1407c62a0, Armor_Penetratio...
    void* field_7; // Used by: Damage_Stats_1401f1a30, Inventory_Base_140b25a80, Inventory_Base...
    void* field_8; // Used by: Damage_Stats_1401f1a30, Reload_Time_14091b240, Damage_Stats_140a...
    void* field_9; // Used by: Damage_Stats_1401f1a30, Reload_Time_14091b240, Armor_Values_1407...
    void* field_a; // Used by: Armor_Penetration, Inventory_Base_140087fa0, Weapon_Accuracy_140...
    void* field_b; // Used by: Armor_Values_1407c62a0, Inventory_Base_140b25a80, Inventory_Base...
    void* field_c; // Used by: Damage_Stats_1401f1a30, Damage_Stats_140a62d30, Armor_Values_140...
    void* field_d; // Used by: Inventory_Base_140b25a80, Inventory_Base_140aff170, Inventory_Ba...
    void* field_e; // Used by: Damage_Stats_1401f1a30, Inventory_Base_140b25a80, Inventory_Base...
    void* field_f; // Used by: Damage_Stats_1401f1a30, Armor_Penetration
    void* field_10; // Used by: Damage_Stats_1401f1a30, Reload_Time_14091b240, Weapon_Accuracy_1...
    void* field_11; // Used by: Reload_Time_14091b240, Armor_Penetration
    void* field_12; // Used by: Reload_Time_14091b240, Inventory_Base_140b249c0, Inventory_Base_...
    void* field_13; // Used by: Reload_Time_14091b240, Armor_Values_1407c6b20, Inventory_Base_14...
    void* field_14; // Used by: Reload_Time_14091b240, Weapon_Accuracy_14096cdb0, Inventory_Base...
    void* field_15; // Used by: Reload_Time_14091b240, Inventory_Base_140b25a80, Armor_Penetrati...
    void* field_16; // Used by: Reload_Time_14091b240, Armor_Values_1407c62a0, Armor_Penetration...
    void* field_17; // Used by: Reload_Time_14091b240, Inventory_Base_140b25a80, Armor_Penetrati...
    void* field_18; // Used by: Damage_Stats_1401f1a30, Reload_Time_14091b240, Armor_Values_1407...
    void* field_19; // Used by: Damage_Stats_1401f1a30, Reload_Time_14091b240, Vehicle_Speed_140...
    void* field_1a; // Used by: Reload_Time_14091b240, Vehicle_Speed_14098e800, Armor_Values_140...
    void* field_1b; // Used by: Reload_Time_14091b240, Armor_Values_140949b50, Armor_Penetration...
    void* field_1c; // Used by: Damage_Stats_1401f1a30, Reload_Time_14091b240, Inventory_Base_14...
    void* field_1d; // Used by: Reload_Time_14091b240, Inventory_Base_140b25a80, Armor_Values_14...
    void* field_1e; // Used by: Reload_Time_1407e4b10, Armor_Values_140949b50, Armor_Penetration
    void* field_1f; // Used by: Armor_Values_140949b50, Armor_Penetration, Damage_Stats_1407dd64...
    void* field_20; // Used by: Damage_Stats_1401f1a30, Reload_Time_14091b240, Armor_Values_1409...
    void* field_21; // Used by: Armor_Penetration, Damage_Stats_1407dd640
    void* field_22; // Used by: Armor_Penetration
    void* field_23; // Used by: Armor_Penetration, Damage_Stats_1407dd640
    void* field_24; // Used by: Armor_Values_140949b50, Weapon_Accuracy_140afbbc0, Armor_Penetra...
    void* field_25; // Used by: Reload_Time_1407e4b10, Armor_Penetration, Damage_Stats_1407dd640
    void* field_26; // Used by: Armor_Penetration
    void* field_27; // Used by: Damage_Stats_1401f1a30, Reload_Time_14091b240, Damage_Stats_140a...
    void* field_28; // Used by: Damage_Stats_1401f1a30, Damage_Stats_140a62d30, Reload_Time_1409...
    void* field_29; // Used by: Inventory_Base_140b25a80, Armor_Penetration, Reload_Time_1403eff...
    void* field_2a; // Used by: Reload_Time_14091b240, Inventory_Base_140b25a80, Armor_Penetrati...
    void* field_2b; // Used by: Inventory_Base_140b25a80, Armor_Penetration, Reload_Time_1403eff...
    void* field_2c; // Used by: Inventory_Base_140aff170, Reload_Time_1407e4b10, Armor_Penetrati...
    void* field_2d; // Used by: Inventory_Base_140aff170, Armor_Penetration, Reload_Time_1403eff...
    void* field_2e; // Used by: Armor_Penetration, Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_2f; // Used by: Armor_Penetration, Physics_Mass_140b1f5f0, Reload_Time_1403eff90...
    void* field_30; // Used by: Damage_Stats_1401f1a30, Reload_Time_14091b240, Armor_Values_1407...
    void* field_31; // Used by: Reload_Time_14091b240, Armor_Values_1407c62a0, Reload_Time_1407e...
    void* field_32; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_33; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_34; // Used by: Reload_Time_1403eff90, Damage_Stats_1407dd640, Weapon_Accuracy_1...
    void* field_35; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_36; // Used by: Reload_Time_1403eff90, Damage_Stats_1407dd640, Armor_Values_1403...
    void* field_37; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_38; // Used by: Damage_Stats_1401f1a30, Reload_Time_14091b240, Inventory_Base_14...
    void* field_39; // Used by: Reload_Time_14091b240, Reload_Time_1403eff90, Armor_Values_1403e...
    void* field_3a; // Used by: Damage_Stats_140a0a180, Reload_Time_1403eff90, Damage_Stats_1407...
    void* field_3b; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90, Armor_Values_1403e...
    void* field_3c; // Used by: Reload_Time_14091b240, Inventory_Base_1409a66e0, Inventory_Base_...
    void* field_3d; // Used by: Inventory_Base_140b249c0, Reload_Time_1403eff90, Armor_Values_14...
    void* field_3e; // Used by: Inventory_Base_140b249c0, Reload_Time_1403eff90, Armor_Values_14...
    void* field_3f; // Used by: Inventory_Base_140b249c0, Reload_Time_1403eff90, Armor_Values_14...
    void* field_40; // Used by: Armor_Values_1407c62a0, Inventory_Base_1409a66e0, Inventory_Base...
    void* field_41; // Used by: Inventory_Base_140b25a80, Inventory_Base_140b249c0, Reload_Time_...
    void* field_42; // Used by: Inventory_Base_140b249c0, Reload_Time_1403eff90, Armor_Values_14...
    void* field_43; // Used by: Inventory_Base_140b249c0, Reload_Time_1403eff90, Armor_Values_14...
    void* field_44; // Used by: Vehicle_Speed_14098e800, Reload_Time_1403eff90, Armor_Values_140...
    void* field_45; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_46; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_47; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_48; // Used by: Reload_Time_14091b240, Armor_Values_1407c62a0, Vehicle_Speed_140...
    void* field_49; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_4a; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_4b; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_4c; // Used by: Vehicle_Speed_14098e800, Reload_Time_1403eff90, Weapon_Accuracy_...
    void* field_4d; // Used by: Inventory_Base_140b25a80, Reload_Time_1403eff90, Armor_Values_14...
    void* field_4e; // Used by: Inventory_Base_140b25a80, Reload_Time_1403eff90, Armor_Values_14...
    void* field_4f; // Used by: Inventory_Base_140b25a80, Reload_Time_1403eff90, Armor_Values_14...
    void* field_50; // Used by: Reload_Time_14091b240, Armor_Values_1407c62a0, Vehicle_Speed_140...
    void* field_51; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_52; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_53; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_54; // Used by: Vehicle_Speed_14098e800, Reload_Time_1403eff90, Armor_Values_140...
    void* field_55; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_56; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_57; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_58; // Used by: Vehicle_Speed_14098e800, Reload_Time_1407e4b10, Reload_Time_1403...
    void* field_59; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_5a; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_5b; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_5c; // Used by: Vehicle_Speed_14098e800, Reload_Time_1403eff90, Armor_Values_140...
    void* field_5d; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_5e; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_5f; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_60; // Used by: Reload_Time_14091b240, Reload_Time_1407e4b10, Damage_Stats_1407d...
    void* field_61; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_62; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_63; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_64; // Used by: Vehicle_Speed_14098e800, Reload_Time_1407e4b10, Physics_Mass_140...
    void* field_65; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_66; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0, Damage_Stats_140b...
    void* field_67; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_68; // Used by: Inventory_Base_1409a66e0, Inventory_Base_140b25a80, Inventory_Ba...
    void* field_69; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_6a; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_6b; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_6c; // Used by: Vehicle_Speed_14098e800, Damage_Stats_1407ddd90, Physics_Mass_14...
    void* field_6d; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_6e; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90, Armor_Values_1403e...
    void* field_6f; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_70; // Used by: Inventory_Base_140aff170, Vehicle_Speed_14098e800, Reload_Time_1...
    void* field_71; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_72; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90, Armor_Values_1403e...
    void* field_73; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_74; // Used by: Reload_Time_1403eff90, Reload_Time_14093a7d0, Armor_Values_1403e...
    void* field_75; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_76; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_77; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_78; // Used by: Vehicle_Speed_14098e800, Weapon_Accuracy_140afbbc0, Inventory_Ba...
    void* field_79; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_7a; // Used by: Armor_Values_1407c62a0, Reload_Time_1403eff90, Armor_Values_1403...
    void* field_7b; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_7c; // Used by: Armor_Values_1407c62a0, Reload_Time_1407e4b10, Reload_Time_1403e...
    void* field_7d; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_7e; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_7f; // Used by: Reload_Time_1403eff90, Reload_Time_14093a7d0, Armor_Values_1403e...
    void* field_80; // Used by: Inventory_Base_140b25a80, Reload_Time_1407e4b10, Weapon_Accuracy...
    void* field_81; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_82; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_83; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_84; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_1403eff90, Armor_Values_1...
    void* field_85; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_86; // Used by: Armor_Values_1407c62a0, Reload_Time_1403eff90, Armor_Values_1403...
    void* field_87; // Used by: Armor_Values_140949b50, Reload_Time_1403eff90, Armor_Values_1403...
    void* field_88; // Used by: Inventory_Base_140b25a80, Vehicle_Speed_14098e800, Damage_Stats_...
    void* field_89; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_8a; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_8b; // Used by: Armor_Values_140949b50, Reload_Time_1403eff90, Armor_Values_1403...
    void* field_8c; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_1403eff90, Armor_Values_1...
    void* field_8d; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_8e; // Used by: Armor_Values_140949b50, Reload_Time_1403eff90, Armor_Values_1403...
    void* field_8f; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_90; // Used by: Weapon_Accuracy_140afbbc0, Inventory_Base_1403a06e0, Reload_Time...
    void* field_91; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_92; // Used by: Reload_Time_14091b240, Reload_Time_1403eff90, Armor_Values_1403e...
    void* field_93; // Used by: Reload_Time_1403eff90, Reload_Time_14093a7d0, Armor_Values_1403e...
    void* field_94; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_1403eff90, Armor_Values_1...
    void* field_95; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_96; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_97; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_98; // Used by: Reload_Time_14095c860, Inventory_Base_140b25a80, Vehicle_Speed_1...
    void* field_99; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_9a; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_9b; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_9c; // Used by: Inventory_Base_140b25a80, Inventory_Base_140aff170, Reload_Time_...
    void* field_9d; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_9e; // Used by: Reload_Time_14091b240, Reload_Time_1403eff90, Armor_Values_1403e...
    void* field_9f; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_a0; // Used by: Inventory_Base_140b25a80, Reload_Time_1407e4b10, Damage_Stats_14...
    void* field_a1; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_a2; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_a3; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_a4; // Used by: Inventory_Base_140b25a80, Weapon_Accuracy_140afbbc0, Damage_Stat...
    void* field_a5; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_a6; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_a7; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_a8; // Used by: Vehicle_Speed_14098e800, Reload_Time_1407e4b10, Damage_Stats_140...
    void* field_a9; // Used by: Damage_Stats_140a0a180, Reload_Time_1403eff90, Armor_Values_1403...
    void* field_aa; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_ab; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_ac; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_1403eff90, Armor_Values_1...
    void* field_ad; // Used by: Reload_Time_1403eff90, Armor_Values_1403e90c0
    void* field_ae; // Used by: Reload_Time_1403eff90
    void* field_af; // Used by: Reload_Time_1403eff90
    void* field_b0; // Used by: Reload_Time_14091b240, Armor_Values_1407c62a0, Reload_Time_14095...
    void* field_b1; // Used by: Reload_Time_1403eff90
    void* field_b2; // Used by: Reload_Time_1403eff90
    void* field_b3; // Used by: Reload_Time_1403eff90
    void* field_b4; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_1403eff90
    void* field_b5; // Used by: Reload_Time_1403eff90
    void* field_b6; // Used by: Reload_Time_1403eff90
    void* field_b7; // Used by: Reload_Time_1403eff90
    void* field_b8; // Used by: Vehicle_Speed_14098e800, Reload_Time_1407e4b10, Damage_Stats_140...
    void* field_b9; // Used by: Reload_Time_1403eff90
    void* field_ba; // Used by: Reload_Time_1403eff90
    void* field_bb; // Used by: Reload_Time_1403eff90
    void* field_bc; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_1403eff90
    void* field_bd; // Used by: Reload_Time_1403eff90
    void* field_be; // Used by: Reload_Time_1403eff90
    void* field_bf; // Used by: Reload_Time_1403eff90
    void* field_c0; // Used by: Damage_Stats_140a0a180, Weapon_Accuracy_140afbbc0, Inventory_Bas...
    void* field_c1; // Used by: Reload_Time_1403eff90
    void* field_c2; // Used by: Reload_Time_1403eff90
    void* field_c3; // Used by: Reload_Time_1403eff90
    void* field_c4; // Used by: Reload_Time_1403eff90
    void* field_c5; // Used by: Reload_Time_1403eff90
    void* field_c6; // Used by: Reload_Time_1403eff90
    void* field_c7; // Used by: Reload_Time_1403eff90
    void* field_c8; // Used by: Vehicle_Speed_14098e800, Reload_Time_1407e4b10, Armor_Values_140...
    void* field_c9; // Used by: Reload_Time_1403eff90
    void* field_ca; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90
    void* field_cb; // Used by: Reload_Time_1403eff90
    void* field_cc; // Used by: Reload_Time_1403eff90, Damage_Stats_140b7a740
    void* field_cd; // Used by: Reload_Time_1403eff90, Damage_Stats_140b7a740
    void* field_ce; // Used by: Reload_Time_1403eff90, Damage_Stats_140b7a740
    void* field_cf; // Used by: Reload_Time_1403eff90, Damage_Stats_140b7a740
    void* field_d0; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90
    void* field_d1; // Used by: Reload_Time_1403eff90
    void* field_d2; // Used by: Reload_Time_1403eff90
    void* field_d3; // Used by: Reload_Time_1403eff90
    void* field_d4; // Used by: Reload_Time_1403eff90
    void* field_d5; // Used by: Reload_Time_1403eff90
    void* field_d6; // Used by: Reload_Time_1403eff90
    void* field_d7; // Used by: Reload_Time_1403eff90
    void* field_d8; // Used by: Vehicle_Speed_14098e800, Weapon_Accuracy_140afbbc0, Reload_Time_...
    void* field_d9; // Used by: Reload_Time_1403eff90
    void* field_da; // Used by: Reload_Time_1403eff90
    void* field_db; // Used by: Reload_Time_1403eff90
    void* field_dc; // Used by: Reload_Time_1403eff90
    void* field_dd; // Used by: Reload_Time_1403eff90
    void* field_de; // Used by: Reload_Time_1403eff90
    void* field_df; // Used by: Reload_Time_1403eff90
    void* field_e0; // Used by: Damage_Stats_1407ddd90, Weapon_Accuracy_140afbbc0, Reload_Time_1...
    void* field_e1; // Used by: Reload_Time_1403eff90
    void* field_e2; // Used by: Reload_Time_1403eff90
    void* field_e3; // Used by: Reload_Time_1403eff90
    void* field_e4; // Used by: Reload_Time_1403eff90
    void* field_e5; // Used by: Reload_Time_1403eff90
    void* field_e6; // Used by: Reload_Time_1403eff90
    void* field_e7; // Used by: Reload_Time_1403eff90
    void* field_e8; // Used by: Vehicle_Speed_14098e800, Damage_Stats_1407ddd90, Damage_Stats_14...
    void* field_e9; // Used by: Reload_Time_1403eff90
    void* field_ea; // Used by: Reload_Time_1403eff90
    void* field_eb; // Used by: Reload_Time_1403eff90
    void* field_ec; // Used by: Damage_Stats_140a0a180, Reload_Time_1403eff90
    void* field_ed; // Used by: Reload_Time_1403eff90
    void* field_ee; // Used by: Reload_Time_1403eff90
    void* field_ef; // Used by: Reload_Time_1403eff90
    void* field_f0; // Used by: Reload_Time_14091b240, Damage_Stats_1407ddd90, Weapon_Accuracy_1...
    void* field_f1; // Used by: Reload_Time_1403eff90
    void* field_f2; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90
    void* field_f3; // Used by: Reload_Time_1403eff90
    void* field_f4; // Used by: Reload_Time_1407e4b10, Weapon_Accuracy_140afbbc0, Reload_Time_14...
    void* field_f5; // Used by: Reload_Time_1403eff90
    void* field_f6; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90
    void* field_f7; // Used by: Reload_Time_1403eff90
    void* field_f8; // Used by: Reload_Time_14091b240, Reload_Time_14095c860, Vehicle_Speed_1409...
    void* field_f9; // Used by: Reload_Time_1403eff90
    void* field_fa; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90
    void* field_fb; // Used by: Reload_Time_1403eff90
    void* field_fc; // Used by: Vehicle_Speed_14098e800, Reload_Time_1407e4b10, Weapon_Accuracy_...
    void* field_fd; // Used by: Reload_Time_1403eff90
    void* field_fe; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90
    void* field_ff; // Used by: Damage_Stats_140a0a180, Reload_Time_1403eff90
    void* field_100; // Used by: Vehicle_Speed_14098e800, Reload_Time_1407e4b10, Weapon_Accuracy_...
    void* field_101; // Used by: Reload_Time_1403eff90
    void* field_102; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90
    void* field_103; // Used by: Reload_Time_1403eff90
    void* field_104; // Used by: Vehicle_Speed_14098e800, Reload_Time_1407e4b10, Reload_Time_1403...
    void* field_105; // Used by: Reload_Time_1403eff90
    void* field_106; // Used by: Reload_Time_14091b240, Reload_Time_1407e4b10, Reload_Time_1403eff90
    void* field_107; // Used by: Reload_Time_1403eff90
    void* field_108; // Used by: Vehicle_Speed_14098e800, Reload_Time_1407e4b10, Weapon_Accuracy_...
    void* field_109; // Used by: Reload_Time_1403eff90
    void* field_10a; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90
    void* field_10b; // Used by: Reload_Time_1403eff90
    void* field_10c; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_1403eff90, Damage_Stats_1...
    void* field_10d; // Used by: Reload_Time_1403eff90
    void* field_10e; // Used by: Reload_Time_1403eff90
    void* field_10f; // Used by: Reload_Time_1403eff90
    void* field_110; // Used by: Weapon_Accuracy_140afbbc0, Inventory_Base_1403a06e0, Reload_Time...
    void* field_111; // Used by: Reload_Time_1403eff90
    void* field_112; // Used by: Reload_Time_14091b240, Reload_Time_1403eff90
    void* field_113; // Used by: Reload_Time_1403eff90
    void* field_114; // Used by: Reload_Time_1403eff90, Damage_Stats_140738830
    void* field_115; // Used by: Reload_Time_1403eff90
    void* field_116; // Used by: Reload_Time_1403eff90
    void* field_117; // Used by: Reload_Time_1403eff90
    void* field_118; // Used by: Armor_Values_1407c62a0, Vehicle_Speed_14098e800, Reload_Time_140...
    void* field_119; // Used by: Reload_Time_1403eff90
    void* field_11a; // Used by: Reload_Time_1403eff90
    void* field_11b; // Used by: Reload_Time_1403eff90
    void* field_11c; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_1403eff90
    void* field_11d; // Used by: Reload_Time_1403eff90
    void* field_11e; // Used by: Reload_Time_1403eff90
    void* field_11f; // Used by: Reload_Time_1403eff90
    void* field_120; // Used by: Weapon_Accuracy_140afbbc0, Inventory_Base_1403a06e0, Reload_Time...
    void* field_121; // Used by: Reload_Time_1403eff90
    void* field_122; // Used by: Reload_Time_1403eff90
    void* field_123; // Used by: Reload_Time_1403eff90
    void* field_124; // Used by: Reload_Time_1403eff90
    void* field_125; // Used by: Reload_Time_1403eff90
    void* field_126; // Used by: Reload_Time_1403eff90
    void* field_127; // Used by: Reload_Time_1403eff90
    void* field_128; // Used by: Vehicle_Speed_14098e800, Armor_Values_140949b50, Weapon_Accuracy...
    void* field_129; // Used by: Reload_Time_1403eff90
    void* field_12a; // Used by: Reload_Time_1403eff90
    void* field_12b; // Used by: Reload_Time_1403eff90
    void* field_12c; // Used by: Reload_Time_1403eff90
    void* field_12d; // Used by: Reload_Time_1403eff90
    void* field_12e; // Used by: Reload_Time_1403eff90
    void* field_12f; // Used by: Reload_Time_1403eff90
    void* field_130; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_1403eff90, Damage_Stats_1...
    void* field_131; // Used by: Reload_Time_1403eff90
    void* field_132; // Used by: Reload_Time_1403eff90
    void* field_133; // Used by: Reload_Time_1403eff90
    void* field_134; // Used by: Reload_Time_1403eff90
    void* field_135; // Used by: Reload_Time_1403eff90
    void* field_136; // Used by: Reload_Time_1403eff90
    void* field_137; // Used by: Reload_Time_1403eff90
    void* field_138; // Used by: Vehicle_Speed_14098e800, Weapon_Accuracy_140afbbc0, Reload_Time_...
    void* field_139; // Used by: Reload_Time_1403eff90
    void* field_13a; // Used by: Reload_Time_1403eff90
    void* field_13b; // Used by: Reload_Time_1403eff90
    void* field_13c; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_1403eff90
    void* field_13d; // Used by: Reload_Time_1403eff90
    void* field_13e; // Used by: Reload_Time_1403eff90
    void* field_13f; // Used by: Reload_Time_1403eff90
    void* field_140; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_1403eff90
    void* field_141; // Used by: Reload_Time_1403eff90
    void* field_142; // Used by: Reload_Time_1403eff90
    void* field_143; // Used by: Reload_Time_1403eff90
    void* field_144; // Used by: Reload_Time_1403eff90
    void* field_145; // Used by: Reload_Time_1403eff90
    void* field_146; // Used by: Reload_Time_1403eff90
    void* field_147; // Used by: Reload_Time_1403eff90
    void* field_148; // Used by: Vehicle_Speed_14098e800, Weapon_Accuracy_140afbbc0, Reload_Time_...
    void* field_149; // Used by: Reload_Time_1403eff90
    void* field_14a; // Used by: Reload_Time_1403eff90
    void* field_14b; // Used by: Reload_Time_1403eff90
    void* field_14c; // Used by: Reload_Time_1403eff90
    void* field_14d; // Used by: Reload_Time_1403eff90
    void* field_14e; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90
    void* field_14f; // Used by: Reload_Time_1403eff90
    void* field_150; // Used by: Damage_Stats_1401f1a30, Reload_Time_1407e4b10, Weapon_Accuracy_1...
    void* field_151; // Used by: Reload_Time_1403eff90
    void* field_152; // Used by: Reload_Time_1403eff90
    void* field_153; // Used by: Reload_Time_1403eff90
    void* field_154; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_1403eff90
    void* field_155; // Used by: Reload_Time_1403eff90
    void* field_156; // Used by: Reload_Time_1407e4b10, Reload_Time_1403eff90
    void* field_157; // Used by: Reload_Time_1403eff90
    void* field_158; // Used by: Vehicle_Speed_14098e800, Weapon_Accuracy_140afbbc0, Reload_Time_...
    void* field_15c; // Used by: Reload_Time_1407e4b10, Weapon_Accuracy_140afbbc0
    void* field_160; // Used by: Damage_Stats_1401f1a30, Weapon_Accuracy_140afbbc0
    void* field_164; // Used by: Weapon_Accuracy_140afbbc0
    void* field_168; // Used by: Vehicle_Speed_14098e800, Weapon_Accuracy_140afbbc0, Armor_Values...
    void* field_16c; // Used by: Weapon_Accuracy_140afbbc0
    void* field_170; // Used by: Damage_Stats_1401f1a30, Weapon_Accuracy_140afbbc0, Physics_Mass_...
    void* field_178; // Used by: Damage_Stats_1401f1a30, Weapon_Accuracy_140afbbc0, Armor_Values_...
    void* field_180; // Used by: Weapon_Accuracy_140afbbc0, Inventory_Base_1403a06e0, Armor_Value...
    void* field_184; // Used by: Weapon_Accuracy_140afbbc0
    void* field_186; // Used by: Reload_Time_14091b240
    void* field_188; // Used by: Weapon_Accuracy_140afbbc0, Armor_Values_140b47820
    void* field_18b; // Used by: Reload_Time_14091b240
    void* field_18c; // Used by: Weapon_Accuracy_140afbbc0
    void* field_190; // Used by: Weapon_Accuracy_140afbbc0, Armor_Values_140b47820
    void* field_194; // Used by: Weapon_Accuracy_140afbbc0
    void* field_195; // Used by: Reload_Time_14091b240
    void* field_197; // Used by: Reload_Time_14091b240
    void* field_198; // Used by: Reload_Time_14091b240, Weapon_Accuracy_140afbbc0, Armor_Values_1...
    void* field_19c; // Used by: Weapon_Accuracy_140afbbc0
    void* field_1a0; // Used by: Weapon_Accuracy_140afbbc0, Armor_Values_140b47820
    void* field_1a4; // Used by: Weapon_Accuracy_140afbbc0
    void* field_1a8; // Used by: Weapon_Accuracy_140afbbc0, Physics_Mass_1407202c0, Armor_Values_...
    void* field_1b0; // Used by: Armor_Values_140b47820
    void* field_1b4; // Used by: Weapon_Accuracy_140afbbc0
    void* field_1b8; // Used by: Reload_Time_14095c860, Physics_Mass_1407202c0, Armor_Values_140b...
    void* field_1c0; // Used by: Reload_Time_1407e4b10, Damage_Stats_140a0a180, Weapon_Accuracy_1...
    void* field_1c8; // Used by: Armor_Values_140b47820
    void* field_1cc; // Used by: Weapon_Accuracy_140afbbc0
    void* field_1d0; // Used by: Weapon_Accuracy_140afbbc0, Inventory_Base_1403a06e0
    void* field_1d4; // Used by: Weapon_Accuracy_140afbbc0
    void* field_1d8; // Used by: Reload_Time_1407e4b10, Weapon_Accuracy_140afbbc0, Armor_Values_1...
    void* field_1dc; // Used by: Weapon_Accuracy_140afbbc0
    void* field_1e0; // Used by: Weapon_Accuracy_140afbbc0, Reload_Time_14093f430, Inventory_Base...
    void* field_1e4; // Used by: Weapon_Accuracy_140afbbc0
    void* field_1e8; // Used by: Weapon_Accuracy_140afbbc0, Inventory_Base_1403a06e0
    void* field_1e9; // Used by: Weapon_Accuracy_140afbbc0
    void* field_1ec; // Used by: Weapon_Accuracy_140afbbc0
    void* field_1f0; // Used by: Weapon_Accuracy_140afbbc0
    void* field_1f8; // Used by: Weapon_Accuracy_140afbbc0, Inventory_Base_1403a06e0
    void* field_1fc; // Used by: Weapon_Accuracy_140afbbc0
    void* field_200; // Used by: Inventory_Base_1403a06e0
    void* field_204; // Used by: Weapon_Accuracy_140afbbc0
    void* field_208; // Used by: Weapon_Accuracy_140afbbc0
    void* field_210; // Used by: Weapon_Accuracy_140afbbc0, Inventory_Base_1403a06e0
    void* field_214; // Used by: Weapon_Accuracy_140afbbc0
    void* field_218; // Used by: Reload_Time_1407e4b10
    void* field_21c; // Used by: Inventory_Base_140b249c0, Weapon_Accuracy_140afbbc0
    void* field_220; // Used by: Weapon_Accuracy_140afbbc0, Inventory_Base_1403a06e0
    void* field_221; // Used by: Inventory_Base_1403a06e0
    void* field_222; // Used by: Inventory_Base_1403a06e0
    void* field_223; // Used by: Inventory_Base_1403a06e0
    void* field_228; // Used by: Weapon_Accuracy_140afbbc0, Inventory_Base_1403a06e0, Armor_Value...
    void* field_22c; // Used by: Weapon_Accuracy_140afbbc0
    void* field_238; // Used by: Inventory_Base_1403a06e0
    void* field_248; // Used by: Inventory_Base_1403a06e0, Damage_Stats_140bb3900
    void* field_250; // Used by: Damage_Stats_1401f1a30
    void* field_258; // Used by: Inventory_Base_1403a06e0
    void* field_260; // Used by: Reload_Time_1407e4b10
    void* field_264; // Used by: Damage_Stats_140738830
    void* field_268; // Used by: Inventory_Base_1403a06e0
    void* field_270; // Used by: Inventory_Base_1403a06e0
    void* field_278; // Used by: Inventory_Base_1403a06e0
    void* field_280; // Used by: Inventory_Base_1403a06e0
    void* field_284; // Used by: Inventory_Base_1403a06e0
    void* field_288; // Used by: Armor_Values_1407c62a0, Inventory_Base_1403a06e0
    void* field_28c; // Used by: Reload_Time_1407e4b10, Inventory_Base_1403a06e0
    void* field_28d; // Used by: Inventory_Base_1403a06e0
    void* field_28e; // Used by: Inventory_Base_1403a06e0
    void* field_290; // Used by: Inventory_Base_1403a06e0
    void* field_298; // Used by: Inventory_Base_1403a06e0
    void* field_29c; // Used by: Inventory_Base_1403a06e0
    void* field_2a0; // Used by: Inventory_Base_1403a06e0
    void* field_2a1; // Used by: Inventory_Base_1403a06e0
    void* field_2a2; // Used by: Inventory_Base_1403a06e0
    void* field_2a3; // Used by: Inventory_Base_1403a06e0
    void* field_2a8; // Used by: Inventory_Base_1403a06e0
    void* field_2b8; // Used by: Inventory_Base_1403a06e0
    void* field_2c8; // Used by: Inventory_Base_1403a06e0
    void* field_2d8; // Used by: Inventory_Base_1403a06e0
    void* field_2e8; // Used by: Reload_Time_14091b240, Armor_Values_140949b50, Physics_Mass_1407...
    uint8_t pad_2f0[0x20];
    void* field_310; // Used by: Damage_Stats_140a0a180
    void* field_318; // Used by: Reload_Time_14095c860, Armor_Values_140949b50
    void* field_320; // Used by: Reload_Time_14095c860, Armor_Values_140949b50
    void* field_328; // Used by: Reload_Time_1407e4b10
    void* field_330; // Used by: Armor_Values_140949b50
    void* field_338; // Used by: Armor_Values_140949b50, Inventory_Base_140362bd0
    void* field_340; // Used by: Inventory_Base_1409d7460
    void* field_344; // Used by: Inventory_Base_1409d7460
    uint8_t pad_34c[0x14];
    void* field_360; // Used by: Reload_Time_1407e4b10
    void* field_363; // Used by: Reload_Time_1407e4b10
    void* field_364; // Used by: Reload_Time_1407e4b10
    void* field_366; // Used by: Reload_Time_1407e4b10
    void* field_368; // Used by: Reload_Time_1407e4b10
    void* field_36a; // Used by: Reload_Time_1407e4b10
    void* field_36c; // Used by: Reload_Time_1407e4b10
    void* field_36e; // Used by: Reload_Time_1407e4b10
    uint8_t pad_376[0x1a];
    void* field_390; // Used by: Damage_Stats_140b7a740
    void* field_398; // Used by: Inventory_Base_1409a66e0, Reload_Time_14093a7d0, Damage_Stats_14...
    void* field_39c; // Used by: Reload_Time_1407e4b10, Reload_Time_14093f430, Reload_Time_14093a7d0
    void* field_3a0; // Used by: Inventory_Base_1409a66e0
    uint8_t pad_3a8[0x10];
    void* field_3b8; // Used by: Reload_Time_14093f430, Reload_Time_14093a7d0
    void* field_3c0; // Used by: Reload_Time_14093f430
    uint8_t pad_3c8[0x14];
    void* field_3dc; // Used by: Reload_Time_14093a7d0
    void* field_3e9; // Used by: Reload_Time_14093f430
    void* field_3ec; // Used by: Reload_Time_14093a7d0
    void* field_3fc; // Used by: Reload_Time_14093a7d0
    void* field_400; // Used by: Damage_Stats_140a5bd50
    uint8_t pad_408[0x14];
    void* field_41c; // Used by: Reload_Time_14095c860
    void* field_420; // Used by: Reload_Time_14095c860
    uint8_t pad_428[0x10];
    void* field_438; // Used by: Damage_Stats_140a0a180
    void* field_440; // Used by: Damage_Stats_140a0a180, Armor_Values_140949b50
    void* field_448; // Used by: Damage_Stats_140a0a180, Armor_Values_140949b50
    void* field_450; // Used by: Damage_Stats_140a0a180
    void* field_458; // Used by: Damage_Stats_140a0a180
    uint8_t pad_460[0x14];
    void* field_474; // Used by: Armor_Values_140949b50
    uint8_t pad_47c[0x2c];
    void* field_4a8; // Used by: Armor_Values_140949b50
    uint8_t pad_4b0[0x20];
    void* field_4d0; // Used by: Physics_Mass_1407202c0
    void* field_4d8; // Used by: Physics_Mass_1407202c0
    uint8_t pad_4e0[0x18];
    void* field_4f8; // Used by: Armor_Values_140949b50
    void* field_508; // Used by: Armor_Values_140949b50
    void* field_510; // Used by: Armor_Values_140949b50
    void* field_518; // Used by: Armor_Values_140949b50
    void* field_520; // Used by: Armor_Values_140949b50
    void* field_528; // Used by: Armor_Values_140949b50, Physics_Mass_1407202c0
    uint8_t pad_530[0x2c];
    void* field_55c; // Used by: Reload_Time_14095c860, Reload_Time_140953570
    void* field_560; // Used by: Armor_Values_140949b50, Physics_Mass_1407202c0
    void* field_568; // Used by: Reload_Time_1407e4b10
    uint8_t pad_570[0x28];
    void* field_598; // Used by: Armor_Values_140949b50
    void* field_599; // Used by: Armor_Values_140949b50
    void* field_59c; // Used by: Armor_Values_140949b50
    void* field_5a0; // Used by: Armor_Values_140949b50
    void* field_5b0; // Used by: Armor_Values_140949b50
    uint8_t pad_5b8[0x10];
    void* field_5c8; // Used by: Armor_Values_140949b50
    uint8_t pad_5d0[0x18];
    void* field_5e8; // Used by: Armor_Values_140949b50
    void* field_5f8; // Used by: Armor_Values_140949b50
    uint8_t pad_600[0x10];
    void* field_610; // Used by: Armor_Values_140949b50
    void* field_618; // Used by: Inventory_Base_1403a06e0
    void* field_620; // Used by: Armor_Values_140949b50
    uint8_t pad_628[0x40];
    void* field_668; // Used by: Armor_Values_140949b50, Inventory_Base_140362bd0
    void* field_66c; // Used by: Armor_Values_140949b50
    void* field_670; // Used by: Armor_Values_140949b50
    uint8_t pad_678[0x40];
    void* field_6b8; // Used by: Inventory_Base_1409a66e0
    void* field_6c0; // Used by: Inventory_Base_1409a66e0
    void* field_6d0; // Used by: Inventory_Base_1409a66e0
    uint8_t pad_6d8[0x188];
    void* field_860; // Used by: Reload_Time_140239b50
    void* field_870; // Used by: Reload_Time_140239b50
    void* field_878; // Used by: Reload_Time_140239b50
    uint8_t pad_880[0xc8];
    void* field_948; // Used by: Inventory_Base_1403a06e0
    void* field_949; // Used by: Inventory_Base_1403a06e0
    void* field_94a; // Used by: Inventory_Base_1403a06e0
    void* field_94c; // Used by: Inventory_Base_1403a06e0
    void* field_954; // Used by: Inventory_Base_1403a06e0
    uint8_t pad_95c[0x3c];
    void* field_998; // Used by: Inventory_Base_140362bd0
    uint8_t pad_9a0[0x30];
    void* field_9d0; // Used by: Reload_Time_14095c860
    uint8_t pad_9d8[0x3c];
    void* field_a14; // Used by: Physics_Mass_1407202c0
    void* field_a18; // Used by: Physics_Mass_1407202c0
    void* field_a24; // Used by: Physics_Mass_140b1f5f0
    uint8_t pad_a2c[0x15c];
    void* field_b88; // Used by: Damage_Stats_140738830
    uint8_t pad_b90[0x12c];
    void* field_cbc; // Used by: Reload_Time_14091b240
    void* field_cc8; // Used by: Inventory_Base_140362bd0
    void* field_cd0; // Used by: Inventory_Base_140362bd0
    uint8_t pad_cd8[0x78];
    void* field_d50; // Used by: Reload_Time_14095c860
    uint8_t pad_d58[0x28];
    void* field_d80; // Used by: Reload_Time_1407e4b10
    void* field_d85; // Used by: Reload_Time_1407e4b10
    void* field_d8c; // Used by: Reload_Time_1407e4b10
    void* field_d90; // Used by: Reload_Time_14095c860
    uint8_t pad_d98[0x18];
    void* field_db0; // Used by: Reload_Time_14095c860, Reload_Time_14093a7d0
    void* field_db8; // Used by: Reload_Time_14095c860
    uint8_t pad_dc0[0xc8];
    void* field_e88; // Used by: Reload_Time_1407e4b10
    uint8_t pad_e90[0x38];
    void* field_ec8; // Used by: Reload_Time_14095c860
    uint8_t pad_ed0[0x668];
    void* field_1538; // Used by: Reload_Time_14095c860
    uint8_t pad_1540[0xe8];
    void* field_1628; // Used by: Damage_Stats_140738830
    uint8_t pad_1630[0x2eac];
    void* field_44dc; // Used by: Reload_Time_14095c860, Reload_Time_1407d9450, Reload_Time_1407e4...
};

// Known specific fields from manual analysis:
// +0xa14 = float mass_component_1
// +0xa18 = float mass_component_2
// +0x1a8 = uint32_t flags
//   bit 5  = simulation_able
//   bit 15-16 = impregnability
//   bit 19 = discovered
