/**
 * Call to Arms: Gates of Hell - Refined Structure Definitions
 * Auto-generated by StructureVerifier.java
 * Based on actual field access patterns in game code
 */

#pragma once
#include <cstdint>

// Common game entity base (offsets 0x00 - 0x40)
struct EntityBase {
    uint8_t _pad_00[0x1];
    void*        field_01; // 423 accesses, read/write
    void*        field_02; // 193 accesses, read
    void*        field_03; // 48 accesses, read/write
    float        field_04; // 159 accesses, read/write
    uint64_t     field_05; // 37 accesses, 
    int16_t      field_06; // 31 accesses, read
    void*        field_07; // 139 accesses, read/write
    float        field_08; // 798 accesses, read/comparison/write
    uint64_t     field_09; // 36 accesses, write
    uint64_t     field_0A; // 30 accesses, 
    uint64_t     field_0B; // 20 accesses, 
    float        field_0C; // 61 accesses, read/comparison/write
    uint64_t     field_0D; // 12 accesses, 
    uint64_t     field_0E; // 9 accesses, 
    void*        field_0F; // 1005 accesses, read/write
    double       field_10; // 925 accesses, comparison/read/write
    uint64_t     field_11; // 36 accesses, write
    void*        field_12; // 43 accesses, read/write
    uint64_t     field_13; // 28 accesses, write
    void*        field_14; // 45 accesses, read/write
    uint64_t     field_15; // 20 accesses, write
    uint64_t     field_16; // 8 accesses, write
    void*        field_17; // 172 accesses, read/comparison/write
    void*        field_18; // 738 accesses, read/comparison/write
    int16_t      field_19; // 121 accesses, read/comparison/write
    int16_t      field_1A; // 27 accesses, read/write
    uint64_t     field_1B; // 16 accesses, write
    void*        field_1C; // 40 accesses, read/comparison/write
    uint64_t     field_1D; // 8 accesses, write
    uint64_t     field_1F; // 208 accesses, write
    double       field_20; // 1548 accesses, read/comparison/write
    uint64_t     field_21; // 10 accesses, write
    uint64_t     field_22; // 4 accesses, 
    uint64_t     field_23; // 6 accesses, write
    float        field_24; // 20 accesses, read/write
    uint64_t     field_25; // 1 accesses, 
    void*        field_27; // 202 accesses, read/write
    void*        field_28; // 544 accesses, read/comparison/write
    uint64_t     field_2A; // 4 accesses, write
    double       field_2C; // 10 accesses, read/write
    uint64_t     field_2D; // 4 accesses, 
    uint64_t     field_2F; // 7 accesses, read/write
    double       field_30; // 974 accesses, read/comparison/write
    uint64_t     field_32; // 2 accesses, 
    uint64_t     field_33; // 1 accesses, 
    uint64_t     field_34; // 14 accesses, read/write
    uint64_t     field_35; // 2 accesses, write
    uint64_t     field_36; // 2 accesses, write
    uint64_t     field_37; // 2 accesses, write
    void*        field_38; // 315 accesses, read/comparison/write
    int16_t      field_39; // 4 accesses, read/write
    uint64_t     field_3A; // 26 accesses, write
    uint64_t     field_3B; // 2 accesses, write
    uint64_t     field_3C; // 40 accesses, read/write
    uint64_t     field_3D; // 2 accesses, write
    uint64_t     field_3E; // 10 accesses, write
    uint64_t     field_3F; // 10 accesses, write
};

// Unit-specific fields (offsets 0x40 - 0xC0)
struct UnitData {
    float        field_40; // 744 accesses, read/comparison/write
    uint64_t     field_41; // 5 accesses, write
    void*        field_44; // 9 accesses, read
    uint64_t     field_47; // 6 accesses, read/write
    void*        field_48; // 443 accesses, read/comparison/write
    void*        field_4C; // 26 accesses, read/write
    uint64_t     field_4F; // 55 accesses, read/write
    float        field_50; // 374 accesses, read/comparison/write
    uint64_t     field_52; // 4 accesses, 
    float        field_54; // 6 accesses, read/write
    void*        field_58; // 252 accesses, read/comparison/write
    float        field_5C; // 6 accesses, read/write
    float        field_60; // 479 accesses, comparison/read/write
    float        field_64; // 25 accesses, read/write
    uint64_t     field_65; // 5 accesses, 
    uint64_t     field_66; // 2 accesses, write
    float        field_67; // 290 accesses, read/comparison/write
    float        field_68; // 196 accesses, read/comparison/write
    float        field_6B; // 16 accesses, read/write
    float        field_6C; // 32 accesses, read/write
    uint64_t     field_6D; // 1 accesses, 
    uint64_t     field_6E; // 3 accesses, write
    float        field_6F; // 427 accesses, read/write
    float        field_70; // 351 accesses, read/comparison/write
    float        field_73; // 16 accesses, read
    float        field_74; // 13 accesses, read/write
    void*        field_75; // 8 accesses, read/write
    void*        field_76; // 8 accesses, comparison/read/write
    float        field_77; // 168 accesses, read/write
    void*        field_78; // 164 accesses, read/comparison/write
    uint64_t     field_79; // 2 accesses, write
    uint64_t     field_7A; // 4 accesses, write
    uint64_t     field_7B; // 4 accesses, write
    uint64_t     field_7C; // 4 accesses, write
    float        field_7F; // 6 accesses, read/write
    void*        field_80; // 138 accesses, read/comparison/write
    uint64_t     field_83; // 2 accesses, write
    void*        field_84; // 4 accesses, read/write
    void*        field_88; // 40 accesses, read/write
    void*        field_8C; // 4 accesses, read/write
    void*        field_90; // 48 accesses, read/comparison/write
    void*        field_94; // 4 accesses, read/write
    void*        field_98; // 38 accesses, read/write
    uint64_t     field_9C; // 2 accesses, write
    void*        field_A0; // 78 accesses, read/comparison/write
    void*        field_A4; // 4 accesses, read/comparison/write
    void*        field_A8; // 23 accesses, read
    void*        field_AC; // 5 accesses, read
    void*        field_B0; // 60 accesses, read/comparison/write
    void*        field_B4; // 2 accesses, read
    void*        field_B8; // 26 accesses, read/comparison/write
    void*        field_BC; // 2 accesses, read
};

// Combat/Weapon fields (offsets 0xC0 - 0x100)
struct CombatData {
    void*        field_C0; // 145 accesses, read/comparison/write
    void*        field_C8; // 39 accesses, read/write
    void*        field_D0; // 61 accesses, read/write
    void*        field_D8; // 22 accesses, read/write
    float        field_E0; // 36 accesses, read/write
    uint8_t _pad_E4[0x4];
    float        field_E8; // 13 accesses, read
    uint8_t _pad_EC[0x3];
    uint64_t     field_EF; // 3 accesses, 
    void*        field_F0; // 24 accesses, read
    uint64_t     field_F2; // 21 accesses, 
    void*        field_F4; // 4 accesses, read
    void*        field_F5; // 2 accesses, read
    void*        field_F6; // 8 accesses, read
    void*        field_F7; // 2 accesses, read
    void*        field_F8; // 28 accesses, read/write
    void*        field_FC; // 6 accesses, read
    uint64_t     field_FD; // 7 accesses, 
    uint64_t     field_FE; // 22 accesses, 
};

// Extended fields (offsets 0x100+)
struct ExtendedData {
    void*        field_100; // 24 accesses, read/write
    uint64_t     field_101; // 16 accesses, 
    void*        field_104; // 4 accesses, read
    void*        field_105; // 2 accesses, read
    void*        field_106; // 2 accesses, read
    void*        field_107; // 2 accesses, read
    void*        field_108; // 26 accesses, read/write
    void*        field_109; // 2 accesses, read
    void*        field_10A; // 2 accesses, read
    void*        field_10B; // 2 accesses, read
    void*        field_10C; // 4 accesses, read
    void*        field_110; // 68 accesses, read/comparison/write
    void*        field_111; // 2 accesses, read
    void*        field_114; // 2 accesses, read
    void*        field_118; // 20 accesses, read/write
    uint64_t     field_119; // 1 accesses, 
    void*        field_11C; // 6 accesses, read
    uint64_t     field_11E; // 2 accesses, 
    void*        field_120; // 14 accesses, read
    uint64_t     field_121; // 2 accesses, 
    uint64_t     field_124; // 2 accesses, 
    uint64_t     field_125; // 2 accesses, 
    void*        field_128; // 12 accesses, read/write
    uint64_t     field_12A; // 1 accesses, 
    uint64_t     field_12B; // 1 accesses, 
    void*        field_130; // 21 accesses, read/write
    uint64_t     field_131; // 1 accesses, 
    void*        field_138; // 24 accesses, read/write
    uint64_t     field_139; // 1 accesses, 
    void*        field_13C; // 4 accesses, read/write
    void*        field_140; // 27 accesses, read/write
    void*        field_141; // 2 accesses, read
    void*        field_142; // 2 accesses, read
    uint64_t     field_144; // 3 accesses, write
    void*        field_148; // 40 accesses, read/write
    uint64_t     field_14C; // 4 accesses, write
    void*        field_150; // 32 accesses, read/write
    void*        field_154; // 2 accesses, read
    void*        field_158; // 11 accesses, read/write
    void*        field_15C; // 2 accesses, read
    void*        field_160; // 13 accesses, read
    void*        field_164; // 6 accesses, read
    void*        field_168; // 21 accesses, read
    void*        field_16C; // 6 accesses, read
    void*        field_170; // 12 accesses, read
    void*        field_174; // 4 accesses, read
    void*        field_178; // 34 accesses, read/write
    void*        field_17C; // 3 accesses, read
    uint64_t     field_17E; // 1 accesses, 
    void*        field_180; // 40 accesses, read/write
    void*        field_184; // 2 accesses, read
    void*        field_188; // 32 accesses, read/write
    void*        field_18C; // 2 accesses, read
    void*        field_190; // 10 accesses, read/write
    void*        field_194; // 2 accesses, read
    uint64_t     field_195; // 1 accesses, 
    void*        field_198; // 28 accesses, read/write
    void*        field_19C; // 2 accesses, read
    void*        field_1A0; // 20 accesses, read/write
    void*        field_1A4; // 2 accesses, read
    uint64_t     field_1A5; // 1 accesses, 
    float        field_1A8; // 20 accesses, read/write
    uint8_t _pad_1AC[0x2];
    uint64_t     field_1AE; // 1 accesses, 
    void*        field_1B0; // 10 accesses, read/write
    void*        field_1B4; // 2 accesses, read
    uint64_t     field_1B8; // 10 accesses, read/write
    void*        field_1C0; // 27 accesses, read/comparison/write
    uint64_t     field_1C4; // 2 accesses, write
    void*        field_1C8; // 44 accesses, read/write
    void*        field_1CC; // 4 accesses, read/write
    void*        field_1D0; // 25 accesses, read/write
    void*        field_1D4; // 2 accesses, read
    void*        field_1D8; // 19 accesses, read/write
    void*        field_1DC; // 2 accesses, read
    void*        field_1E0; // 90 accesses, read/write
    void*        field_1E4; // 2 accesses, read
    void*        field_1E8; // 102 accesses, read/comparison/write
    void*        field_1E9; // 2 accesses, read
    void*        field_1EC; // 2 accesses, read
    uint64_t     field_1ED; // 1 accesses, 
    void*        field_1F0; // 72 accesses, read/write
    uint64_t     field_1F5; // 1 accesses, 
    void*        field_1F8; // 26 accesses, read/write
    void*        field_1FC; // 2 accesses, read
    void*        field_200; // 17 accesses, read/write
    void*        field_204; // 2 accesses, read
    void*        field_208; // 22 accesses, read/comparison/write
    void*        field_210; // 13 accesses, read
    void*        field_214; // 2 accesses, read
    void*        field_218; // 16 accesses, read
    void*        field_21C; // 4 accesses, read
    void*        field_220; // 13 accesses, read
    void*        field_224; // 2 accesses, read
    void*        field_228; // 4 accesses, read
    void*        field_22C; // 2 accesses, read
    void*        field_230; // 16 accesses, read/write
    uint64_t     field_238; // 6 accesses, read/write
    uint64_t     field_23B; // 1 accesses, 
    void*        field_240; // 29 accesses, read/write
    void*        field_248; // 14 accesses, read/comparison/write
    uint64_t     field_24F; // 1 accesses, 
    void*        field_250; // 24 accesses, read/write
    uint64_t     field_257; // 1 accesses, 
    uint64_t     field_258; // 12 accesses, read/write
    uint64_t     field_25F; // 1 accesses, 
    void*        field_260; // 16 accesses, read/write
    uint64_t     field_268; // 12 accesses, read/write
    void*        field_270; // 8 accesses, read
    void*        field_274; // 2 accesses, read
    void*        field_278; // 18 accesses, read/write
    void*        field_280; // 20 accesses, read/write
    uint64_t     field_288; // 12 accesses, read/write
    void*        field_290; // 22 accesses, read/write
    void*        field_298; // 16 accesses, read/write
    void*        field_2A0; // 22 accesses, read/write
    uint64_t     field_2A8; // 6 accesses, write
    uint64_t     field_2AC; // 8 accesses, comparison/write
    void*        field_2B0; // 6 accesses, read/write
    uint64_t     field_2B8; // 7 accesses, write
    void*        field_2C0; // 6 accesses, read/write
    void*        field_2C8; // 6 accesses, read/write
    uint64_t     field_2D0; // 4 accesses, write
    uint64_t     field_2D8; // 4 accesses, write
    void*        field_2DC; // 8 accesses, read
    void*        field_2E0; // 10 accesses, read/write
    uint64_t     field_2E4; // 4 accesses, write
    uint64_t     field_2E8; // 86 accesses, read/write
    uint64_t     field_2EC; // 4 accesses, write
    void*        field_2F0; // 24 accesses, read/write
    uint64_t     field_2F4; // 4 accesses, write
    void*        field_2F8; // 8 accesses, read/write
    uint64_t     field_300; // 10 accesses, read/write
    uint64_t     field_308; // 8 accesses, read/write
    uint8_t _pad_310[0x20];
    void*        field_330; // 6 accesses, read
    void*        field_338; // 2 accesses, read
    void*        field_340; // 2 accesses, read
    uint8_t _pad_348[0x8];
    float        field_350; // 4 accesses, write
    uint8_t _pad_354[0x4];
    uint64_t     field_358; // 1 accesses, 
    uint8_t _pad_360[0x10];
    uint64_t     field_370; // 2 accesses, write
    float        field_378; // 2 accesses, write
    float        field_37C; // 2 accesses, write
    float        field_380; // 7 accesses, read/write
    float        field_384; // 2 accesses, write
    float        field_388; // 2 accesses, write
    uint8_t _pad_38C[0x4];
    void*        field_390; // 2 accesses, read
    uint64_t     field_398; // 4 accesses, read/write
    uint64_t     field_3A0; // 4 accesses, read/comparison
    float        field_3A8; // 4 accesses, write
    float        field_3AC; // 2 accesses, write
    float        field_3B0; // 2 accesses, write
    float        field_3B4; // 2 accesses, write
    float        field_3B8; // 2 accesses, write
    void*        field_3BC; // 2 accesses, read
    void*        field_3C0; // 4 accesses, read
    uint8_t _pad_3C8[0x8];
    void*        field_3D0; // 6 accesses, read
    uint8_t _pad_3D8[0x18];
    float        field_3F0; // 8 accesses, read/write
    uint8_t _pad_3F4[0x4];
    float        field_3F8; // 20 accesses, read/write
    uint8_t _pad_3FC[0x4];
    void*        field_400; // 17 accesses, read/comparison/write
    uint64_t     field_402; // 1 accesses, 
    uint64_t     field_403; // 1 accesses, 
    float        field_408; // 10 accesses, read/write
    uint8_t _pad_40C[0x6];
    uint64_t     field_412; // 1 accesses, 
    void*        field_418; // 2 accesses, read
    uint64_t     field_420; // 6 accesses, comparison/write
    uint64_t     field_428; // 2 accesses, 
    uint8_t _pad_430[0x10];
    void*        field_440; // 6 accesses, read
    float        field_448; // 4 accesses, read/write
    uint8_t _pad_44C[0x4];
    void*        field_450; // 12 accesses, read/write
    uint64_t     field_453; // 1 accesses, 
    uint8_t _pad_45B[0xD];
    uint64_t     field_468; // 3 accesses, write
    uint64_t     field_46A; // 1 accesses, 
    uint64_t     field_470; // 2 accesses, write
    uint64_t     field_478; // 2 accesses, write
    uint64_t     field_480; // 2 accesses, write
    void*        field_488; // 4 accesses, read/write
    void*        field_490; // 6 accesses, read/write
    uint64_t     field_492; // 2 accesses, write
    void*        field_498; // 2 accesses, read
    uint8_t _pad_4A0[0x8];
    uint64_t     field_4A8; // 2 accesses, 
    uint8_t _pad_4B0[0x10];
    void*        field_4C0; // 6 accesses, read
    uint8_t _pad_4C8[0x28];
    void*        field_4F0; // 4 accesses, read
    void*        field_4F8; // 4 accesses, read
    uint64_t     field_500; // 2 accesses, read
    void*        field_508; // 4 accesses, read
    uint64_t     field_510; // 2 accesses, read
    uint64_t     field_518; // 2 accesses, read
    void*        field_51C; // 2 accesses, read
    uint64_t     field_520; // 2 accesses, read
    uint64_t     field_528; // 2 accesses, 
    uint8_t _pad_530[0x8];
    uint64_t     field_538; // 2 accesses, 
    void*        field_540; // 4 accesses, read/write
    uint64_t     field_548; // 2 accesses, write
    uint64_t     field_550; // 2 accesses, write
    uint64_t     field_558; // 6 accesses, read/write
    uint64_t     field_560; // 4 accesses, read/write
    void*        field_564; // 2 accesses, read
    uint64_t     field_568; // 2 accesses, write
    void*        field_570; // 4 accesses, read
    uint8_t _pad_578[0x8];
    void*        field_580; // 2 accesses, read
    void*        field_588; // 2 accesses, read
    uint8_t _pad_590[0x1C];
    void*        field_5AC; // 2 accesses, read
    uint8_t _pad_5B4[0x1C];
    void*        field_5D0; // 2 accesses, read
    uint8_t _pad_5D8[0x10];
    void*        field_5E8; // 4 accesses, read/write
    uint64_t     field_5F0; // 16 accesses, comparison/write
    void*        field_5F4; // 8 accesses, comparison/read/write
    void*        field_5F8; // 6 accesses, read/write
    uint64_t     field_600; // 4 accesses, read/write
    void*        field_608; // 4 accesses, read
    uint8_t _pad_610[0x8];
    void*        field_618; // 6 accesses, read
    uint64_t     field_620; // 2 accesses, comparison/write
    void*        field_628; // 2 accesses, read
    uint64_t     field_630; // 4 accesses, read/write
    uint64_t     field_638; // 4 accesses, read/comparison
    uint64_t     field_640; // 2 accesses, write
    uint64_t     field_644; // 2 accesses, write
    uint8_t _pad_64C[0x14];
    void*        field_660; // 2 accesses, read
    uint8_t _pad_668[0x8];
    void*        field_670; // 2 accesses, read
    void*        field_678; // 12 accesses, read
    uint64_t     field_680; // 2 accesses, comparison/write
    uint64_t     field_688; // 2 accesses, read
    uint8_t _pad_690[0x48];
    void*        field_6D8; // 2 accesses, read
    uint8_t _pad_6E0[0x8];
    void*        field_6E8; // 2 accesses, read
    uint8_t _pad_6F0[0x60];
    void*        field_750; // 2 accesses, read
    uint8_t _pad_758[0x8];
    void*        field_760; // 2 accesses, read
    uint8_t _pad_768[0x60];
    void*        field_7C8; // 4 accesses, read
    uint8_t _pad_7D0[0x8];
    void*        field_7D8; // 2 accesses, read
    uint8_t _pad_7E0[0x38];
    void*        field_818; // 2 accesses, read
    uint8_t _pad_820[0x8];
    void*        field_828; // 4 accesses, read/write
    void*        field_830; // 4 accesses, read/write
    void*        field_838; // 4 accesses, read/write
    uint64_t     field_840; // 2 accesses, write
    void*        field_848; // 4 accesses, read/write
    uint64_t     field_850; // 2 accesses, write
    void*        field_858; // 8 accesses, read/write
    void*        field_860; // 6 accesses, read/write
    uint64_t     field_864; // 2 accesses, write
    void*        field_868; // 3 accesses, read
    uint64_t     field_870; // 2 accesses, read
    void*        field_878; // 4 accesses, comparison/read/write
    uint8_t _pad_880[0x8];
    void*        field_888; // 2 accesses, read
    void*        field_890; // 2 accesses, read
    void*        field_898; // 2 accesses, read
    uint8_t _pad_8A0[0x8];
    void*        field_8A8; // 2 accesses, read
    uint8_t _pad_8B0[0x8];
    void*        field_8B8; // 4 accesses, read
    uint8_t _pad_8C0[0x8];
    void*        field_8C8; // 2 accesses, read
    uint8_t _pad_8D0[0x8];
    uint64_t     field_8D8; // 4 accesses, read/write
    uint64_t     field_8E0; // 4 accesses, read/write
    uint64_t     field_8E8; // 4 accesses, read/write
    void*        field_8F0; // 6 accesses, read
    uint8_t _pad_8F8[0x8];
    void*        field_900; // 6 accesses, read
    uint8_t _pad_908[0x8];
    uint64_t     field_910; // 4 accesses, read/write
    void*        field_918; // 2 accesses, read
    uint8_t _pad_920[0x8];
    void*        field_928; // 2 accesses, read
    uint8_t _pad_930[0x8];
    void*        field_938; // 6 accesses, read
    uint8_t _pad_940[0x8];
    void*        field_948; // 6 accesses, read
    uint8_t _pad_950[0x8];
    void*        field_958; // 6 accesses, read
    uint8_t _pad_960[0x8];
    void*        field_968; // 6 accesses, read
    uint8_t _pad_970[0x8];
    void*        field_978; // 4 accesses, read
    uint8_t _pad_980[0x20];
    void*        field_9A0; // 2 accesses, read
    uint8_t _pad_9A8[0x8];
    void*        field_9B0; // 2 accesses, read
    uint8_t _pad_9B8[0x8];
    void*        field_9C0; // 6 accesses, read
    uint8_t _pad_9C8[0x8];
    void*        field_9D0; // 6 accesses, read
    uint8_t _pad_9D8[0x18];
    uint64_t     field_9F0; // 1 accesses, 
    uint8_t _pad_9F8[0x18];
    void*        field_A10; // 2 accesses, read
    uint8_t _pad_A18[0x4];
    uint64_t     field_A1C; // 2 accesses, write
    uint64_t     field_A23; // 2 accesses, comparison/write
    uint64_t     field_C00; // 2 accesses, 
    uint8_t _pad_C08[0x28];
    uint64_t     field_C30; // 4 accesses, read/comparison
    uint8_t _pad_C38[0x8];
    uint64_t     field_C40; // 1 accesses, 
    uint8_t _pad_C48[0x10];
    void*        field_C58; // 2 accesses, read
    uint8_t _pad_C60[0x58];
    int16_t      field_CB8; // 4 accesses, read/write
    uint8_t _pad_CBA[0x2];
    float        field_CBC; // 2 accesses, write
    void*        field_CC0; // 2 accesses, read
    uint8_t _pad_CC8[0xF0];
    uint64_t     field_DB8; // 2 accesses, read
    uint8_t _pad_DC0[0x80];
    uint64_t     field_E40; // 2 accesses, 
    uint8_t _pad_E48[0x78];
    uint64_t     field_EC0; // 8 accesses, 
};
