/**
 * Call to Arms: Gates of Hell - Virtual Function Tables
 * Auto-generated by VTableHunter.java
 */

#pragma once
#include <cstdint>

namespace COA {
namespace VTables {

constexpr uintptr_t Unknown_VTable_140fe78d8 = 0x0fe78d8; // 1398 refs, 4 methods
constexpr uintptr_t Unknown_VTable_14113e308 = 0x113e308; // 860 refs, 3 methods
constexpr uintptr_t AI_VTable = 0x0fe7858; // 678 refs, 3 methods
constexpr uintptr_t Unknown_VTable_140fe79b0 = 0x0fe79b0; // 624 refs, 3 methods
constexpr uintptr_t Vehicle_AI_VTable = 0x0fe6960; // 448 refs, 9 methods
constexpr uintptr_t Unknown_VTable_140ff4900 = 0x0ff4900; // 406 refs, 4 methods
constexpr uintptr_t Unknown_VTable_14113e0f8 = 0x113e0f8; // 320 refs, 3 methods
constexpr uintptr_t Movement_AI_Controller_VTable = 0x0fe6ae0; // 250 refs, 16 methods
constexpr uintptr_t Unknown_VTable_1410049b8 = 0x10049b8; // 238 refs, 4 methods
constexpr uintptr_t Unknown_VTable_14113f710 = 0x113f710; // 234 refs, 3 methods
constexpr uintptr_t Unknown_VTable_140fe7900 = 0x0fe7900; // 228 refs, 9 methods
constexpr uintptr_t Unknown_VTable_140fe7950 = 0x0fe7950; // 228 refs, 11 methods
constexpr uintptr_t Unknown_VTable_140fffe50 = 0x0fffe50; // 228 refs, 10 methods
constexpr uintptr_t AI_VTable = 0x0fe6a40; // 218 refs, 16 methods
constexpr uintptr_t Unknown_VTable_141003d90 = 0x1003d90; // 210 refs, 16 methods
constexpr uintptr_t Unknown_VTable_141005560 = 0x1005560; // 193 refs, 12 methods
constexpr uintptr_t Unknown_VTable_1411a0f20 = 0x11a0f20; // 192 refs, 3 methods
constexpr uintptr_t Unknown_VTable_1410b9348 = 0x10b9348; // 176 refs, 3 methods
constexpr uintptr_t Unknown_VTable_14113f6f0 = 0x113f6f0; // 160 refs, 3 methods
constexpr uintptr_t Unknown_VTable_141144f18 = 0x1144f18; // 157 refs, 3 methods
constexpr uintptr_t Unknown_VTable_1410fdc18 = 0x10fdc18; // 152 refs, 14 methods
constexpr uintptr_t Unknown_VTable_1410fdc90 = 0x10fdc90; // 152 refs, 4 methods
constexpr uintptr_t Unknown_VTable_141008bf0 = 0x1008bf0; // 151 refs, 9 methods
constexpr uintptr_t Unknown_VTable_14104ef50 = 0x104ef50; // 150 refs, 3 methods
constexpr uintptr_t Vehicle_AI_Object_Controller_Squad_VTable = 0x0febbc8; // 148 refs, 5 methods
constexpr uintptr_t AI_Controller_VTable = 0x0fea370; // 143 refs, 4 methods
constexpr uintptr_t Vehicle_AI_Object_Controller_Squad_VTable = 0x0febc08; // 141 refs, 5 methods
constexpr uintptr_t Unknown_VTable_140feab38 = 0x0feab38; // 131 refs, 4 methods
constexpr uintptr_t Unknown_VTable_140fea8a0 = 0x0fea8a0; // 130 refs, 69 methods
constexpr uintptr_t Unknown_VTable_140feaaf8 = 0x0feaaf8; // 130 refs, 4 methods
constexpr uintptr_t Unknown_VTable_14113eb80 = 0x113eb80; // 130 refs, 3 methods
constexpr uintptr_t Unknown_VTable_1411981d0 = 0x11981d0; // 110 refs, 3 methods
constexpr uintptr_t Unknown_VTable_141175a28 = 0x1175a28; // 106 refs, 4 methods
constexpr uintptr_t Unknown_VTable_141008b80 = 0x1008b80; // 101 refs, 9 methods
constexpr uintptr_t AI_Controller_VTable = 0x0fe8518; // 99 refs, 5 methods
constexpr uintptr_t Unknown_VTable_141122d28 = 0x1122d28; // 98 refs, 3 methods
constexpr uintptr_t Unknown_VTable_141143058 = 0x1143058; // 98 refs, 3 methods
constexpr uintptr_t Unknown_VTable_1411a6448 = 0x11a6448; // 96 refs, 3 methods
constexpr uintptr_t Unknown_VTable_1410b9c58 = 0x10b9c58; // 94 refs, 5 methods
constexpr uintptr_t Unknown_VTable_141190a28 = 0x1190a28; // 93 refs, 4 methods
constexpr uintptr_t Unknown_VTable_141004380 = 0x1004380; // 92 refs, 5 methods
constexpr uintptr_t Unknown_VTable_141143f08 = 0x1143f08; // 84 refs, 39 methods
constexpr uintptr_t Unknown_VTable_141040430 = 0x1040430; // 82 refs, 4 methods
constexpr uintptr_t Unknown_VTable_1410061c8 = 0x10061c8; // 80 refs, 10 methods
constexpr uintptr_t AI_Controller_VTable = 0x0fe8558; // 76 refs, 73 methods
constexpr uintptr_t AI_Controller_VTable = 0x0fe87d0; // 76 refs, 4 methods
constexpr uintptr_t Unknown_VTable_141040458 = 0x1040458; // 76 refs, 4 methods
constexpr uintptr_t Unknown_VTable_14113f730 = 0x113f730; // 76 refs, 3 methods
constexpr uintptr_t Unknown_VTable_141142410 = 0x1142410; // 76 refs, 3 methods
constexpr uintptr_t Unknown_VTable_140fe98d8 = 0x0fe98d8; // 74 refs, 72 methods
constexpr uintptr_t Unknown_VTable_140fe9b48 = 0x0fe9b48; // 74 refs, 4 methods
constexpr uintptr_t Unknown_VTable_1410057b0 = 0x10057b0; // 70 refs, 30 methods
constexpr uintptr_t Unknown_VTable_14118fe98 = 0x118fe98; // 68 refs, 3 methods
constexpr uintptr_t Unknown_VTable_141040480 = 0x1040480; // 67 refs, 4 methods
constexpr uintptr_t Unknown_VTable_14113e0b0 = 0x113e0b0; // 62 refs, 3 methods
constexpr uintptr_t Unknown_VTable_141176940 = 0x1176940; // 62 refs, 3 methods
constexpr uintptr_t Unknown_VTable_140fffdf0 = 0x0fffdf0; // 61 refs, 10 methods
constexpr uintptr_t Unknown_VTable_140ffcc38 = 0x0ffcc38; // 60 refs, 70 methods
constexpr uintptr_t Unknown_VTable_140ffce98 = 0x0ffce98; // 60 refs, 4 methods
constexpr uintptr_t Unknown_VTable_1411023d0 = 0x11023d0; // 58 refs, 4 methods
constexpr uintptr_t Unknown_VTable_1410460e8 = 0x10460e8; // 56 refs, 6 methods
constexpr uintptr_t Unknown_VTable_141054e88 = 0x1054e88; // 54 refs, 5 methods
constexpr uintptr_t Unknown_VTable_1410ae520 = 0x10ae520; // 50 refs, 4 methods
constexpr uintptr_t Unknown_VTable_14113eb60 = 0x113eb60; // 50 refs, 3 methods
constexpr uintptr_t Unknown_VTable_14113f750 = 0x113f750; // 50 refs, 3 methods
constexpr uintptr_t Unknown_VTable_14119c5d8 = 0x119c5d8; // 50 refs, 3 methods
constexpr uintptr_t AI_Controller_VTable = 0x10058c8; // 48 refs, 31 methods
constexpr uintptr_t Unknown_VTable_1410a4a30 = 0x10a4a30; // 48 refs, 4 methods
constexpr uintptr_t Unknown_VTable_1410c89d0 = 0x10c89d0; // 48 refs, 6 methods
constexpr uintptr_t Unknown_VTable_1410a49e8 = 0x10a49e8; // 46 refs, 8 methods
constexpr uintptr_t Unknown_VTable_1410b1868 = 0x10b1868; // 46 refs, 11 methods
constexpr uintptr_t Unknown_VTable_1410e4bd0 = 0x10e4bd0; // 46 refs, 70 methods
constexpr uintptr_t Unknown_VTable_1410e4e30 = 0x10e4e30; // 46 refs, 4 methods
constexpr uintptr_t Unknown_VTable_1410136b8 = 0x10136b8; // 44 refs, 9 methods
constexpr uintptr_t Unknown_VTable_141107e38 = 0x1107e38; // 44 refs, 3 methods
constexpr uintptr_t Unknown_VTable_141043868 = 0x1043868; // 42 refs, 11 methods
constexpr uintptr_t Unknown_VTable_141195410 = 0x1195410; // 42 refs, 3 methods
constexpr uintptr_t Unknown_VTable_140ffc330 = 0x0ffc330; // 41 refs, 4 methods
constexpr uintptr_t AI_Team_VTable = 0x102fec0; // 41 refs, 4 methods
constexpr uintptr_t Unknown_VTable_141142508 = 0x1142508; // 41 refs, 6 methods
constexpr uintptr_t Unknown_VTable_1410142a8 = 0x10142a8; // 40 refs, 9 methods
constexpr uintptr_t Unknown_VTable_14105ad80 = 0x105ad80; // 40 refs, 76 methods
constexpr uintptr_t Unknown_VTable_14105b020 = 0x105b020; // 40 refs, 4 methods
constexpr uintptr_t Unknown_VTable_1410c8a08 = 0x10c8a08; // 38 refs, 6 methods
constexpr uintptr_t Unknown_VTable_1410cf5d8 = 0x10cf5d8; // 38 refs, 5 methods
constexpr uintptr_t Unknown_VTable_141122db0 = 0x1122db0; // 38 refs, 4 methods
constexpr uintptr_t Unknown_VTable_140fe6e98 = 0x0fe6e98; // 36 refs, 19 methods
constexpr uintptr_t Unknown_VTable_1411443a8 = 0x11443a8; // 36 refs, 3 methods
constexpr uintptr_t Unknown_VTable_1411424d0 = 0x11424d0; // 35 refs, 6 methods
constexpr uintptr_t Unknown_VTable_140ff2330 = 0x0ff2330; // 34 refs, 75 methods
constexpr uintptr_t Unknown_VTable_140ff25b8 = 0x0ff25b8; // 34 refs, 4 methods
constexpr uintptr_t Unknown_VTable_140ff25f8 = 0x0ff25f8; // 34 refs, 4 methods
constexpr uintptr_t Unknown_VTable_14117a1d0 = 0x117a1d0; // 34 refs, 4 methods
constexpr uintptr_t Unknown_VTable_1410280a8 = 0x10280a8; // 33 refs, 5 methods
constexpr uintptr_t Unknown_VTable_1410404a8 = 0x10404a8; // 33 refs, 4 methods
constexpr uintptr_t Unknown_VTable_1410a4fb8 = 0x10a4fb8; // 32 refs, 16 methods
constexpr uintptr_t Unknown_VTable_140fe6c90 = 0x0fe6c90; // 30 refs, 10 methods
constexpr uintptr_t Unknown_VTable_141179d28 = 0x1179d28; // 30 refs, 7 methods
constexpr uintptr_t Unknown_VTable_140fe69b0 = 0x0fe69b0; // 29 refs, 16 methods
constexpr uintptr_t Unknown_VTable_14104f140 = 0x104f140; // 29 refs, 15 methods
constexpr uintptr_t Unknown_VTable_1410a4868 = 0x10a4868; // 29 refs, 16 methods

} // namespace VTables
} // namespace COA
